name: Build and push to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY_IMAGE: vincejv/nginx

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            # set latest tag for default branch
            type=raw,value=${{ matrix.march }}-ubuntu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve commit
        id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: | 
            ${{ env.REGISTRY_IMAGE }}:latest
            ${{ env.REGISTRY_IMAGE }}:${{ steps.commit.outputs.short }}
            ghcr.io/${{ env.REGISTRY_IMAGE }}:latest
            ghcr.io/${{ env.REGISTRY_IMAGE }}:${{ steps.commit.outputs.short }}